### PR TITLE
Fix flaky system test

### LINKED ISSUE #9: Fix flaky test
There is a test in `semantic_search_system_test.rb` that is flaky and not always passing.

### PR DESCRIPTION
**Pull request by shindi-renuo**
Fixes #9

### CODE REVIEW

File: test/system/semantic_search_system_test.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def setup
 
     EmbeddingService.any_instance.stubs(:generate_embedding).returns([0.1] * 1536)
 
-    mock_result = [{
+    @mock_result = [{
```
Comment (shindi-renuo) [inline test/system/semantic_search_system_test.rb:32]: Is it necessary to make it an instance variable? not really.
